# Define manager
/MG/manager/mglog error
/MG/manager/seedWithDevRandom

# Define processes
/MG/processes/realm BBdecay
#/MG/processes/optical true
/MG/processes/lowenergy true
/MG/processes/useNoHadPhysics true

### Geometry ###
/MG/geometry/detector GerdaArray
/MG/geometry/database false
/MG/geometry/detector/general/depth 0 cm

### Set 7 string Phase II lock ###
/MG/geometry/lock/type PhaseII_DN500
/MG/geometry/lock/dn500/n_strings 7
/MG/geometry/lock/dn500/string_distance 11.0 cm

### Geometry and Matrix files ###
/MG/geometry/detector/geometryfile geometry_PhaseII_FCCD_growth.dat
/MG/geometry/detector/matrixfile matrix_phase_ii_StatusDec2015_pos.dat
/MG/geometry/general/constructsupport true
/MG/geometry/general/constructcabling true

### Construct liquid Argon veto and electronics plate ###
### This activates automatically the optical processes ###
/MG/geometry/general/constructLArInstrumentation true
/MG/geometry/LArInst/SelectDesign hybrid
#/MG/geometry/LArInst/PhotonTracking false

### Nylon Minishrouds ###
/MG/geometry/general/constructMiniShroud true
/MG/geometry/general/miniShroudMaterial Nylon
/MG/geometry/LArInst/MinisShroudOpticalCoating TPB
/MG/geometry/general/adjustMinishroudToDetctorString true
/MG/geometry/general/miniShroudBaseThickness 0.125 mm
/MG/geometry/general/miniShroudSideThickness 0.125 mm

### Individual z positions defined in second column of matrix file ###
/MG/geometry/detector/individualzposofdetectors true
/MG/geometry/detector/crystal/reverse true

### Muon Veto ###
/MG/geometry/cherenkov -1

### Output ###
/MG/eventaction/reportingfrequency 10000
/MG/eventaction/rootschema GSS
/MG/eventaction/rootfilename ./gedet/surf/ver/ver-gedet-surf-14.root

/run/initialize

/MG/generator/select GSS
#/MG/generator/confine volume

/MG/io/gss/addVolume CrystalDeadLayer_geometry5_12

/MG/generator/gss/origin -55 95.2628 -68.9047 cm
/MG/generator/gss/boundingR 52.06 mm

/MG/io/gss/setMaxIntersections 4

## Define run
/tracking/verbose 0
/run/beamOn 30000000
