# load preamble
/control/execute				./gedet/intrinsic_chanwise/0nbb_0p1/coin/log/preamble.mac

/MG/eventaction/rootfilename			./gedet/intrinsic_chanwise/0nbb_0p1/coin/raw-gedet-intrinsic_chanwise-0nbb_0p1-coin-ch29.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/MG/geometry/cherenkov				-1

/run/initialize

/MG/generator/confine				volumearray
/MG/generator/volumearrayadd			CrystalDeadLayer_geometry11_9
/MG/generator/volumearrayadd			Crystal_geometry11_9

/MG/generator/select				decay0
/MG/generator/decay0/filename			./decay0files/0nbb_0p1_1E7.dk0

/tracking/verbose				0
/run/beamOn					6461327
