# load preamble
/control/execute                           ./lar/above_ms2/K42/coin/log/preamble.mac

/MG/eventaction/rootfilename               ./lar/above_ms2/K42/coin/raw-lar-above_ms2-K42-coin-047.root
#/MG/output/WriteMacroToOutput             true                ### is default ###
#/MG/output/WriteNumberOfEventsToFile      true                ### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit true
/MG/output/saveOnlyEventsWithCoincidence   true

/run/initialize

### Confine source volume to cryo LAr ###
/MG/generator/confine                           volume
/MG/generator/volume                            CryoLiquidPhysical

### A cylinder inside the LAr ###
/MG/generator/Sampling/volume/name                     Cylinder
/MG/generator/Sampling/volume/innerCylinderRadius      0 mm
/MG/generator/Sampling/volume/outerCylinderRadius      5 cm
/MG/generator/Sampling/volume/cylinderHeight           10 cm
/MG/generator/Sampling/volume/offsetCenterXPos         55.0 mm
/MG/generator/Sampling/volume/offsetCenterYPos         95.2628 mm
/MG/generator/Sampling/volume/offsetCenterZPos         143.9 mm

/MG/generator/select G4gun
/MG/generator/g4gun/cone_on true
/gun/particle ion
/gun/ion 19 42
/gun/energy 0 eV

/tracking/verbose                          0
/run/beamOn                                100000000
