language: julia
julia:
    - 1.1

git:
  submodules: false

before_install:
    - julia -e 'import Pkg; Pkg.add("JSON")'

install: true

script:
    - julia UTILS/health-dep/mac-doctor.jl
    - julia UTILS/health-dep/meta-doctor.jl
