# load preamble
/control/execute				./gedet/intrinsic_chanwise/2nbb_2p1/coin/log/preamble.mac

/MG/eventaction/rootfilename			./gedet/intrinsic_chanwise/2nbb_2p1/coin/raw-gedet-intrinsic_chanwise-2nbb_2p1-coin-ch39.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/MG/geometry/cherenkov				-1

/run/initialize

/MG/generator/confine				volumearray
/MG/generator/volumearrayadd			CrystalDeadLayer_geometry11_3
/MG/generator/volumearrayadd			Crystal_geometry11_3

/MG/generator/select				decay0
/MG/generator/decay0/filename			./decay0files/2nbb_2p1_1E7.dk0

/tracking/verbose				0
/run/beamOn					576791
