# load preamble
/control/execute				./cables/sig_at_holders/Pa234m/coin/log/preamble.mac

/MG/eventaction/rootfilename			./cables/sig_at_holders/Pa234m/coin/raw-cables-sig_at_holders-Pa234m-coin-010.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/run/initialize

/MG/generator/confine				volumelist
/MG/generator/volumelistfrom			0
/MG/generator/volumelistto			39
/MG/generator/volumelist			SignalCableAtHolder_Phase2

/MG/generator/select				G4gun
/MG/generator/g4gun/cone_on			true
/gun/particle					ion
/gun/ion					91 234 #Pa234m#
/gun/energy					0 eV

/tracking/verbose				0
/run/beamOn					10000000
