# load preamble
/control/execute				./minishroud/ms3_tub/K40/coin/log/preamble.mac

/MG/eventaction/rootfilename			./minishroud/ms3_tub/K40/coin/raw-minishroud-ms3_tub-K40-coin-031.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/run/initialize

/MG/generator/confine				volume
/MG/generator/volume			MiniShroudPhase2Tub_2

/MG/generator/select				G4gun
/MG/generator/g4gun/cone_on			true
/gun/particle					ion
/gun/ion					19 40 #K40#
/gun/energy					0 eV

/tracking/verbose				0
/run/beamOn					10000000
