# load preamble
/control/execute				./gedet/nplus/K42/coin/log/preamble.mac

/MG/eventaction/rootfilename			./gedet/nplus/K42/coin/raw-gedet-nplus-K42-coin-ch7.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/run/initialize

/MG/generator/gsspositionsfile			gedet/nplus/ver/ver-gedet-nplus-ch7.root

/MG/generator/select				G4gun
/MG/generator/g4gun/cone_on			true
/gun/particle					ion
/gun/ion					19 42 #K42#
/gun/energy					0 eV

/tracking/verbose				0
/run/beamOn					1000000
