#!/bin/bash
#
# USAGE: qsub mpik-run-mage.qsub <mage-macro-file>
#
#$ -P short ### queue
#$ -j y     ### have logoutput and erroroutput in the same file
#$ -o /dev/null
#$ -e /dev/null

container=gerda-sw-all_active.simg

logfile=$(echo $1 | cut -f 1 -d '.').out
gerda_ms=$(echo $1 | rev | cut -f7- -d'/' | rev)
cd $gerda_ms
/usr/bin/time -v singularity exec --cleanenv ./UTILS/container/$container MaGe --no-colors $1 &> $logfile
