#!/bin/bash

#$ -P short	### queue
#$ -j y		### have logoutput and erroroutput in the same file
#$ -o /dev/null
#$ -e /dev/null

SRCDIR=/lfs/l2/gerda/gerda-simulations/gerda-mage-sim
LOGFILE=$2/$1/pdf-$1.out

mkdir -p $2/$1
singularity exec $SRCDIR/UTILS/container/gerda-mage-sim-utils.sqsh pdf-gen-volume \
  --destdir $2 \
  --ged-mapping $SRCDIR/UTILS/det-data/ged-mapping.json \
  $1 &> $LOGFILE
