# load preamble
/control/execute				./cables/hv_cables/Bi207/coin/log/preamble.mac

/MG/eventaction/rootfilename			./cables/hv_cables/Bi207/coin/raw-cables-hv_cables-Bi207-coin-012.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/run/initialize

/MG/generator/confine				volumelist
/MG/generator/volumelistfrom			0
/MG/generator/volumelistto			39
/MG/generator/volumelist			HVCableFromHolderToElectronicsPlate_Phase2

/MG/generator/select				G4gun
/MG/generator/g4gun/cone_on			true
/gun/particle					ion
/gun/ion					83 207 #Bi207#
/gun/energy					0 eV

/tracking/verbose				0
/run/beamOn					10000000
