# load preamble
/control/execute				./minishroud/bottoms/Pa234m/coin/log/preamble.mac

/MG/eventaction/rootfilename			./minishroud/bottoms/Pa234m/coin/raw-minishroud-bottoms-Pa234m-coin-038.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/run/initialize

/MG/generator/confine				volumelist
/MG/generator/volumelistfrom			0
/MG/generator/volumelistto			6
/MG/generator/volumelist			MiniShroudPhase2Bottom

/MG/generator/select				G4gun
/MG/generator/g4gun/cone_on			true
/gun/particle					ion
/gun/ion					91 234 #Pa234m#
/gun/energy					0 eV

/tracking/verbose				0
/run/beamOn					10000000
