title: gerda-mage-sim online browser
description: Here you can check the status of the GERDA's MaGe simulation campaign.
baseurl: /gerda-mage-sim
url: https://mppmu.github.io
github_username: mppmu
show_downloads: false
logo: assets/img/logo.png

markdown: kramdown
theme: jekyll-theme-minimal

plugins:
    - "jekyll-github-metadata"
