# load preamble
/control/execute				./minishroud/ms2_tub/K42/coin/log/preamble.mac

/MG/eventaction/rootfilename			./minishroud/ms2_tub/K42/coin/raw-minishroud-ms2_tub-K42-coin-067.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/run/initialize

/MG/generator/confine				volume
/MG/generator/volume			MiniShroudPhase2Tub_1

/MG/generator/select				G4gun
/MG/generator/g4gun/cone_on			true
/gun/particle					ion
/gun/ion					19 42 #K42#
/gun/energy					0 eV

/tracking/verbose				0
/run/beamOn					10000000
