#=
 = create-lar-pplus-macros.jl
 =
 = Author:  Katharina von Sturm - vonsturm@pd.infn.it
 = Created: 08 Jan 2018
 =
 =#
import JSON

# check if everything is ok
isfile("./create-lar-pplus-macros.jl") || error("Please run this script from where create-lar-pplus-macros.jl is!")

length(ARGS) < 1 && error("Usage ./create-lar-pplus-macros.jl ISOTOPE")

for f in ["../gedet/lar_pplus/$(ARGS[1])/edep/log/raw-gedet-lar_pplus-$(ARGS[1])-edep-%DET.tmac", "det-data/ged-mapping.json", "det-data/ged-parameters.json"]
    isfile(f) || error("$f not found!")
end

# get dictionaries for gedet
gedMap = JSON.parsefile("det-data/ged-mapping.json")["mapping"]
gedPar = JSON.parsefile("det-data/ged-parameters.json")
# get template macro file
temLines = readlines(open("../gedet/lar_pplus/$(ARGS[1])/edep/log/raw-gedet-lar_pplus-$(ARGS[1])-edep-%DET.tmac"))

# loop over detectors in ged-mapping file with a (key,value) pair
for (det, info) in gedMap
    CHANNEL = info["channel"]
    INNERRADIUS = "0 mm"
    OUTERRADIUS = string(gedPar[det]["groove_inner_radius"]) * " mm"
    XPOS = string(gedPar[det]["detcenter_x"]) * " mm"
    YPOS = string(gedPar[det]["detcenter_y"]) * " mm"

    if contains( det, "GD" )
        HEIGHT = "5 mm"
        ZPOS = string(gedPar[det]["detcenter_z"] - gedPar[det]["height"]/2.0 - 2.5) * " mm"
    elseif contains( det, "ANG" ) || contains( det, "RG" ) || contains( det, "GTF" )
        HEIGHT = string(gedPar[det]["pplus_length_z"] + 5) * " mm"
        ZPOS = string(gedPar[det]["detcenter_z"] - gedPar[det]["height"]/2.0 - 2.5 + gedPar[det]["pplus_length_z"]/2.0) * " mm"
    end

        macLines = temLines
        macLines = replace.(macLines, "\$CHANNEL", CHANNEL)
        macLines = replace.(macLines, "\$INNERRADIUS", INNERRADIUS)
        macLines = replace.(macLines, "\$OUTERRADIUS", OUTERRADIUS)
        macLines = replace.(macLines, "\$HEIGHT", HEIGHT)
        macLines = replace.(macLines, "\$XPOS", XPOS)
        macLines = replace.(macLines, "\$YPOS", YPOS)
        macLines = replace.(macLines, "\$ZPOS", ZPOS)

    unshift!(macLines, "")
    unshift!(macLines, "#This macro was auto-generated by the create-lar-pplus-macros.jl script")

    writedlm(open("../gedet/lar_pplus/$(ARGS[1])/edep/log/raw-gedet-lar_pplus-$(ARGS[1])-edep-ch$CHANNEL.mac", "w"), macLines, '\n')
    println("created ../gedet/lar_pplus/$(ARGS[1])/edep/log/raw-gedet-lar_pplus-$(ARGS[1])-edep-ch$CHANNEL.mac")
end
