# load preamble
/control/execute				./minishroud/glue_rings_bottom/K40/coin/log/preamble.mac

/MG/eventaction/rootfilename			./minishroud/glue_rings_bottom/K40/coin/raw-minishroud-glue_rings_bottom-K40-coin-057.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/run/initialize

/MG/generator/confine				volumelist
/MG/generator/volumelistfrom			0
/MG/generator/volumelistto			6
/MG/generator/volumelist			MiniShroudPhase2BottomGluedRing

/MG/generator/select				G4gun
/MG/generator/g4gun/cone_on			true
/gun/particle					ion
/gun/ion					19 40 #K40#
/gun/energy					0 eV

/tracking/verbose				0
/run/beamOn					10000000
