# load preamble
/control/execute				./minishroud/glue_ring2/Bi214/coin/log/preamble.mac

/MG/eventaction/rootfilename			./minishroud/glue_ring2/Bi214/coin/raw-minishroud-glue_ring2-Bi214-coin-047.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/run/initialize

/MG/generator/confine		      		volumearray
/MG/generator/volumearrayadd      MiniShroudPhase2BottomGluedRing_1
/MG/generator/volumearrayadd      MiniShroudPhase2TopGluedRing_1

/MG/generator/select				G4gun
/MG/generator/g4gun/cone_on			true
/gun/particle					ion
/gun/ion					83 214 #Bi214#
/gun/energy					0 eV

/tracking/verbose				0
/run/beamOn					10000000
