# load preamble
/control/execute				./gedet/intrinsic_chanwise/0nbb_0p1/edep/log/preamble.mac

/MG/eventaction/rootfilename			./gedet/intrinsic_chanwise/0nbb_0p1/edep/raw-gedet-intrinsic_chanwise-0nbb_0p1-edep-ch6.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	false

/MG/geometry/cherenkov				-1

/run/initialize

/MG/generator/confine				volumearray
/MG/generator/volumearrayadd			CrystalDeadLayer_geometry5_7
/MG/generator/volumearrayadd			Crystal_geometry5_7

/MG/generator/select				decay0
/MG/generator/decay0/filename			./decay0files/0nbb_0p1_1E7.dk0

/tracking/verbose				0
/run/beamOn					1831469
