# load preamble
/control/execute				./larveto/fibers/Pa234m/coin/log/preamble.mac

/MG/eventaction/rootfilename			./larveto/fibers/Pa234m/coin/raw-larveto-fibers-Pa234m-coin-012.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/MG/geometry/cherenkov				-1

/run/initialize

/MG/generator/confine				volume
/MG/generator/volume				LArInstr_FiberOuter_Physical

/MG/generator/select				G4gun
/MG/generator/g4gun/cone_on			true
/gun/particle					ion
/gun/ion					91 234 #Pa234m#
/gun/energy					0 eV

/tracking/verbose				0
/run/beamOn					10000000
