# load preamble
/control/execute				./larveto/sipm_ring/Bi212/coin/log/preamble.mac

/MG/eventaction/rootfilename			./larveto/sipm_ring/Bi212/coin/raw-larveto-sipm_ring-Bi212-coin-001.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/MG/geometry/cherenkov				-1

/run/initialize


/MG/generator/select				G4gun
/MG/generator/g4gun/cone_on			true
/gun/particle					ion
/gun/ion					83 212 #Bi212#
/gun/energy					0 eV

/tracking/verbose				0
/run/beamOn					10000000
