# ================================================ #
# GERDA Phase-II crosscheck macro                  #
# K.v.Sturm 25.01.2018                             #
# ================================================ #

### manager ###
/tracking/verbose                               0
/MG/manager/mglog                               trace
/MG/manager/seedWithDevRandom

### processes ###
/MG/processes/realm                             BBdecay     ### Candidates: BBdecay, DarkMatter, CosmicRay ##
/MG/processes/lowenergy                         true
/MG/processes/useNoHadPhysics                   true

### Geometry ###
/MG/geometry/detector                           Dario
/MG/geometry/database                           false

### Output ###
/MG/eventaction/reportingfrequency              10000
/MG/eventaction/rootschema                      Dario

/MG/eventaction/rootfilename               	Dario_Ac228_dk0.root

/run/initialize

### Confine source volume to cryo LAr ###
/MG/generator/confine                           volume
/MG/generator/volume                            crystal

/MG/generator/select                       	decay0
/MG/generator/decay0/filename             	../../decay0files/Ac228_1E7.dk0

/tracking/verbose                          	0
/run/beamOn                                	1000000
