# ================================================ #
# GERDA Phase-II crosscheck macro                  #
# K.v.Sturm 25.01.2018                             #
# ================================================ #

### manager ###
/tracking/verbose                               0
/MG/manager/mglog                               trace
/MG/manager/seedWithDevRandom

### processes ###
/MG/processes/realm                             BBdecay     ### Candidates: BBdecay, DarkMatter, CosmicRay ##
/MG/processes/lowenergy                         true
/MG/processes/useNoHadPhysics                   true

### Geometry ###
/MG/geometry/detector                           Dario
/MG/geometry/database                           false

### Output ###
/MG/eventaction/reportingfrequency              10000
/MG/eventaction/rootschema                      Dario

/MG/eventaction/rootfilename               	Dario_Kr85_g4.root

/run/initialize

### Confine source volume to cryo LAr ###
/MG/generator/confine                           volume
/MG/generator/volume                            crystal

/MG/generator/select 		G4gun
/MG/generator/g4gun/cone_on 	true
/gun/particle 			ion
/gun/ion 			36 85
/gun/energy 			0 eV 

/tracking/verbose                          	0
/run/beamOn                                	1000000
