# load preamble
/control/execute				./minishroud/glue_ring7_top/K40/coin/log/preamble.mac

/MG/eventaction/rootfilename			./minishroud/glue_ring7_top/K40/coin/raw-minishroud-glue_ring7_top-K40-coin-037.root
#/MG/output/WriteMacroToOutput			true		### is default ###
#/MG/output/WriteNumberOfEventsToFile		true		### is default ###

/MG/output/saveOnlyEventsWithEnergyDeposit	true
/MG/output/saveOnlyEventsWithCoincidence	true

/run/initialize

/MG/generator/confine		      		volumearray
/MG/generator/volumearrayadd      MiniShroudPhase2TopGluedRing_6

/MG/generator/select				G4gun
/MG/generator/g4gun/cone_on			true
/gun/particle					ion
/gun/ion					19 40 #K40#
/gun/energy					0 eV

/tracking/verbose				0
/run/beamOn					10000000
